/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.uni_hannover.hci.turing_machine;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Test public void testAppHasAGreeting() {
        // App classUnderTest = new App();
        assertNotNull("app should have a greeting", "dummy");
    }
}
